# Generated by Django 3.0 on 2019-12-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='satelite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Satelite'),
        ),
    ]
