# Generated by Django 3.0 on 2019-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
